// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wal.proto

package wal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	Ts                   *HybridTimestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Tombstone            bool             `protobuf:"varint,2,opt,name=Tombstone,proto3" json:"Tombstone,omitempty"`
	Key                  string           `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Val                  []byte           `protobuf:"bytes,4,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6364fc8077884f, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTs() *HybridTimestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Entry) GetTombstone() bool {
	if m != nil {
		return m.Tombstone
	}
	return false
}

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type HybridTimestamp struct {
	Wall                 int64    `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Logical              int64    `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HybridTimestamp) Reset()         { *m = HybridTimestamp{} }
func (m *HybridTimestamp) String() string { return proto.CompactTextString(m) }
func (*HybridTimestamp) ProtoMessage()    {}
func (*HybridTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6364fc8077884f, []int{1}
}

func (m *HybridTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HybridTimestamp.Unmarshal(m, b)
}
func (m *HybridTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HybridTimestamp.Marshal(b, m, deterministic)
}
func (m *HybridTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybridTimestamp.Merge(m, src)
}
func (m *HybridTimestamp) XXX_Size() int {
	return xxx_messageInfo_HybridTimestamp.Size(m)
}
func (m *HybridTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_HybridTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_HybridTimestamp proto.InternalMessageInfo

func (m *HybridTimestamp) GetWall() int64 {
	if m != nil {
		return m.Wall
	}
	return 0
}

func (m *HybridTimestamp) GetLogical() int64 {
	if m != nil {
		return m.Logical
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "main.Entry")
	proto.RegisterType((*HybridTimestamp)(nil), "main.HybridTimestamp")
}

func init() { proto.RegisterFile("wal.proto", fileDescriptor_ae6364fc8077884f) }

var fileDescriptor_ae6364fc8077884f = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4f, 0xcc, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x2a, 0xe0, 0x62, 0x75,
	0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x52, 0xe5, 0x62, 0x2a, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x36, 0x12, 0xd5, 0x03, 0xc9, 0xe9, 0x79, 0x54, 0x26, 0x15, 0x65, 0xa6, 0x84, 0x64, 0xe6, 0xa6,
	0x16, 0x97, 0x24, 0xe6, 0x16, 0x04, 0x31, 0x95, 0x14, 0x0b, 0xc9, 0x70, 0x71, 0x86, 0xe4, 0xe7,
	0x26, 0x15, 0x97, 0xe4, 0xe7, 0xa5, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0x21, 0x04, 0x84,
	0x04, 0xb8, 0x98, 0xbd, 0x53, 0x2b, 0x25, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90,
	0x48, 0x58, 0x62, 0x8e, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x88, 0xa9, 0x64, 0xcf, 0xc5,
	0x8f, 0x66, 0xb0, 0x90, 0x10, 0x17, 0x4b, 0x79, 0x62, 0x4e, 0x0e, 0xd8, 0x76, 0xe6, 0x20, 0x30,
	0x5b, 0x48, 0x82, 0x8b, 0x3d, 0x27, 0x3f, 0x3d, 0x33, 0x39, 0x31, 0x07, 0x6c, 0x0d, 0x73, 0x10,
	0x8c, 0xeb, 0xc4, 0x1a, 0xc5, 0x5c, 0x9e, 0x98, 0x93, 0xc4, 0x06, 0xf6, 0x86, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x3f, 0x9d, 0x83, 0x34, 0xd3, 0x00, 0x00, 0x00,
}
