// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mvcc.proto

package mvcc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoElement struct {
	Ts                   *ProtoHybridTimestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Tombstone            bool                  `protobuf:"varint,2,opt,name=Tombstone,proto3" json:"Tombstone,omitempty"`
	Key                  string                `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Val                  []byte                `protobuf:"bytes,4,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtoElement) Reset()         { *m = ProtoElement{} }
func (m *ProtoElement) String() string { return proto.CompactTextString(m) }
func (*ProtoElement) ProtoMessage()    {}
func (*ProtoElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbc00ddc884ba4f, []int{0}
}

func (m *ProtoElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoElement.Unmarshal(m, b)
}
func (m *ProtoElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoElement.Marshal(b, m, deterministic)
}
func (m *ProtoElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoElement.Merge(m, src)
}
func (m *ProtoElement) XXX_Size() int {
	return xxx_messageInfo_ProtoElement.Size(m)
}
func (m *ProtoElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoElement.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoElement proto.InternalMessageInfo

func (m *ProtoElement) GetTs() *ProtoHybridTimestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *ProtoElement) GetTombstone() bool {
	if m != nil {
		return m.Tombstone
	}
	return false
}

func (m *ProtoElement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProtoElement) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type ProtoHybridTimestamp struct {
	Wall                 int64    `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Logical              int64    `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoHybridTimestamp) Reset()         { *m = ProtoHybridTimestamp{} }
func (m *ProtoHybridTimestamp) String() string { return proto.CompactTextString(m) }
func (*ProtoHybridTimestamp) ProtoMessage()    {}
func (*ProtoHybridTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbc00ddc884ba4f, []int{1}
}

func (m *ProtoHybridTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoHybridTimestamp.Unmarshal(m, b)
}
func (m *ProtoHybridTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoHybridTimestamp.Marshal(b, m, deterministic)
}
func (m *ProtoHybridTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoHybridTimestamp.Merge(m, src)
}
func (m *ProtoHybridTimestamp) XXX_Size() int {
	return xxx_messageInfo_ProtoHybridTimestamp.Size(m)
}
func (m *ProtoHybridTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoHybridTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoHybridTimestamp proto.InternalMessageInfo

func (m *ProtoHybridTimestamp) GetWall() int64 {
	if m != nil {
		return m.Wall
	}
	return 0
}

func (m *ProtoHybridTimestamp) GetLogical() int64 {
	if m != nil {
		return m.Logical
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoElement)(nil), "main.ProtoElement")
	proto.RegisterType((*ProtoHybridTimestamp)(nil), "main.ProtoHybridTimestamp")
}

func init() { proto.RegisterFile("mvcc.proto", fileDescriptor_5dbc00ddc884ba4f) }

var fileDescriptor_5dbc00ddc884ba4f = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2d, 0x4b, 0x4e,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xaa, 0xe1, 0xe2,
	0x09, 0x00, 0x71, 0x5d, 0x73, 0x52, 0x73, 0x53, 0xf3, 0x4a, 0x84, 0xb4, 0xb8, 0x98, 0x4a, 0x8a,
	0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x40, 0x4a, 0xf4, 0xc0, 0xf2, 0x1e, 0x95,
	0x49, 0x45, 0x99, 0x29, 0x21, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x41, 0x4c, 0x25,
	0xc5, 0x42, 0x32, 0x5c, 0x9c, 0x21, 0xf9, 0xb9, 0x49, 0xc5, 0x25, 0xf9, 0x79, 0xa9, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x08, 0x01, 0x21, 0x01, 0x2e, 0x66, 0xef, 0xd4, 0x4a, 0x09, 0x66,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x13, 0x24, 0x12, 0x96, 0x98, 0x23, 0xc1, 0xa2, 0xc0, 0xa8,
	0xc1, 0x13, 0x04, 0x62, 0x2a, 0xb9, 0x70, 0x89, 0x60, 0x33, 0x5d, 0x48, 0x88, 0x8b, 0xa5, 0x3c,
	0x31, 0x27, 0x07, 0xec, 0x0e, 0xe6, 0x20, 0x30, 0x5b, 0x48, 0x82, 0x8b, 0x3d, 0x27, 0x3f, 0x3d,
	0x33, 0x39, 0x31, 0x07, 0x6c, 0x17, 0x73, 0x10, 0x8c, 0xeb, 0xc4, 0x16, 0xc5, 0x02, 0xf2, 0x57,
	0x12, 0x1b, 0xd8, 0x63, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x48, 0x04, 0x61, 0xe6,
	0x00, 0x00, 0x00,
}
